### ISSUE TITLE
Überarbeitetes Projekt

### ISSUE THREAD

**Issue by Shajiryan** [th-koeln-optec-messsysteme/Turbulenzmessung#1]
@bazjo 

Hallo Johannes, Wir haben jetzt 4 Vertikal Plots gemacht, in der wir uns verschiedene Werte über die Höhe anschauen. Wir haben unseren neuen Code hochgeladen und auch 1 Screenshot (new Plotted Data.png), wie unsere Plots jetzt ausschauen.

Soll das so sein, wie es in den Screenshots ist, oder soll das anders aussehen? 
ist bei den Achsen auch alles in Ordnung?
Zur Vereinfachung der Analyse, lassen sich alle Ordinaten gleichzeitig verschieben.

Liebe Grüße,
Shayan

**Comment by bazjo** [comment]
Das sieht gut aus. Evtl noch Taupunkt berechnen und die Temperatur/Taupunkt/andere Werte in einem Diagramm überlagern, aber das muss nicht unbedingt sein
